bool NewTarget
int32 ControlGroup
int32 BaseGroup
float64 Period
int32 PlannerMethod
geometry_msgs/Transform TargetTransform
geometry_msgs/Vector3 Reference1
geometry_msgs/Vector3 Reference2
float64 TargetElbowAngle
bool Grip
---
bool inProgress
bool isReachable
bool isAccepted
